# Generated by Django 4.1 on 2022-09-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video'},
        ),
    ]
