# Generated by Django 4.1 on 2022-09-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0002_alter_videos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
