# Generated by Django 4.1 on 2022-09-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0004_videos_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_games', models.CharField(max_length=50)),
                ('link_games', models.CharField(max_length=100)),
                ('desc_games', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appMain.materia')),
            ],
            options={
                'verbose_name': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividades', models.CharField(max_length=50)),
                ('link_atividades', models.CharField(max_length=100)),
                ('desc_atividades', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appMain.materia')),
            ],
            options={
                'verbose_name': 'Atividades',
            },
        ),
    ]
