# Generated by Django 4.1 on 2022-09-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0005_games_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
